# This is a configuration file for the Shopify CLI
project_type: theme

# Development store URL
store: mktest-theme.myshopify.com

# Your theme ID will be generated when you first run 'shopify theme dev'
# theme_id: 12345678

# Optional: Theme editor URL defaults
# editor_sync:
#   container_path: src
#   preview_path: assets
