# Theme configuration file for Shopify CLI
# https://shopify.dev/themes/tools/cli/theme-configuration

development:
  store: your-store.myshopify.com
  password: shppa_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  theme_id: "12345678"
  # For more options, see the documentation link above
